name: local_package_functional_tests

# This test will run on every pull request, and on every commit on any branch
on:
        [push, pull_request]

jobs:
    functional_tests:
        name: Run functional tests using Behat
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    tools: composer:v2
                    extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv

            -   name: Setup Drupal
                run: |
                    COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:~8 ~/drupal --no-interaction
                    cd ~/drupal
                    composer config minimum-stability dev
                    composer config prefer-stable true
                    composer config preferred-install dist
                    composer config repositories.0 "{\"type\": \"path\", \"url\": \"$GITHUB_WORKSPACE\", \"options\": {\"symlink\": false}}"
                    composer config repositories.1 composer https://packages.drupal.org/8
                    COMPOSER_MEMORY_LIMIT=-1 composer require drupal/core-dev:~8 --with-all-dependencies
            -   name: Install drupal-rector
                run: |
                    cd ~/drupal
                    composer require palantirnet/drupal-rector:@dev --no-progress

            -   name: Copy rector config
                run: |
                    cd ~/drupal
                    cp vendor/palantirnet/drupal-rector/rector.php .
                    cat rector.php

            -   name: Prepare rector_examples folder in the drupal modules directory
                run: |
                  cd ~/drupal
                  mkdir -p web/modules/custom
                  mv vendor/palantirnet/drupal-rector/rector_examples web/modules/custom
                  ls -la web/modules/custom/rector_examples

            -   name: Run rector against Drupal (dry-run)
                run: |
                    cd ~/drupal
                    vendor/bin/rector process web/modules/custom/rector_examples --dry-run --debug
            -   name: Run rector against Drupal
                run: |
                    cd ~/drupal
                    vendor/bin/rector process web/modules/custom/rector_examples --debug
            -    run: diff -rubB rector_examples_updated ~/drupal/web/modules/custom/rector_examples
