name: phpunit
on: [push, pull_request]
jobs:
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    tools: composer:v2
                    extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
            -    run: composer install
            -    run: composer create-project drupal/recommended-project:^8.9 tests/fixtures/drupal
            -    run: vendor/bin/phpunit
