name: unit_tests__phpunit

# This test will run on every pull request, and on every commit on any branch
on: [push, pull_request]

jobs:
    run_unit_tests_with_phpunit:
        name: Run unit tests with PHPUnit
# START: SHARED SETUP
        runs-on: ubuntu-latest  
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    tools: composer:v2
                    extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
            # Uncomment to enable SSH access to Github Actions - https://github.com/marketplace/actions/debugging-with-tmate#getting-started
            # -   name: Debugging with tmate
            #     uses: mxschmitt/action-tmate@v2
# END: SHARED SETUP
            -    run: composer install
            -    run: composer create-project drupal/recommended-project:^8.9 tests/fixtures/drupal
            -    run: vendor/bin/phpunit
